services:
  backend:
    build: .
    container_name: resume
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-*arjb)#7!62o+3xi$9ag@46b^hju#wf_06sfne_-f@aao0rt98
      - DEBUG=True
      