# Generated by Django 4.2.17 on 2024-12-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['-created_date'], 'verbose_name': 'Contact'},
        ),
    ]
